(function(){if(typeof BLANK_IMG=='undefined')
var BLANK_IMG='';String.prototype.namespace=function(separator){this.split(separator||'.').inject(window,function(parent,child){var o=parent[child]={};return o;});};'EM.tools'.namespace();EM.tools.roundedCorner=function(selector){$$(selector).each(function(el){$(el).addClassName('em-rounded');$(el).insert({top:'<span class="tl"> </span><span class="tm"> </span><span class="tr"> </span><span class="ml"> </span><span class="mm"> </span><span class="mr"> </span><span class="bl"> </span><span class="bm"> </span><span class="br"> </span>'});});};EM.tools.roundedCornerTextBox=function(){$$('.input-text').each(function(el){if(Element.visible(el)&&!el.hasClassName('qty')){$(el).relativize();$(el.parentNode).addClassName('em-rounded');$(el.parentNode).insert({top:'<span class="tl"> </span><span class="tm"> </span><span class="tr"> </span><span class="ml"> </span><span class="mm"> </span><span class="mr"> </span><span class="bl"> </span><span class="bm"> </span><span class="br"> </span>'});}});};function decorateCatalogProductView(){if(Element.hasClassName(document.body,'catalog-product-view')){$$('.short-description h2, .product-collateral h2').each(function(el){el.innerHTML='<span>'+el.innerHTML+'</span>';});}}
document.observe("dom:loaded",function(){decorateCatalogProductView();});document.observe('dom:loaded',function(){var show=new protoShow('myshow',{captions:true,});});})();jQuery(document).ready(function(){jQuery("#nav2>li,#nav2>li>a").mouseenter(function(){jQuery("#nav2>li>ul").show();});jQuery("#nav2>li, #nav2>li>ul").mouseleave(function(){jQuery("#nav2>li>ul").hide();});jQuery('.minimal-slider').easySlider({auto:true,continuous:true,speed:800,pause:10000,controlsFade:true,numeric:true});function distance(x0,y0,x1,y1){var xDiff=x1-x0;var yDiff=y1-y0;return Math.sqrt(xDiff*xDiff+yDiff*yDiff);}
var proximity=230;var iconSmall=180,iconLarge=230;var iconDiff=(iconLarge-iconSmall);var mouseX,mouseY;var dock=jQuery("#dock");var dock1=jQuery("#dock1");var dock2=jQuery("#dock2");var animating=false,redrawReady=false;jQuery(document.body).removeClass("no_js");jQuery(document).bind("mousemove",function(e){if(dock.is(":visible")){mouseX=e.pageX;mouseY=e.pageY;redrawReady=true;registerConstantCheck();}
if(dock1.is(":visible")){mouseX=e.pageX;mouseY=e.pageY;redrawReady=true;registerConstantCheck();}
if(dock2.is(":visible")){mouseX=e.pageX;mouseY=e.pageY;redrawReady=true;registerConstantCheck();}});function registerConstantCheck(){if(!animating){animating=true;window.setTimeout(callCheck,1);}}
function callCheck(){sizeDockIcons();animating=false;if(redrawReady){redrawReady=false;registerConstantCheck();}}
function sizeDockIcons(){dock.find("li").each(function(){var centerX=jQuery(this).offset().left+(jQuery(this).outerWidth()/2.0);var centerY=jQuery(this).offset().top+(jQuery(this).outerHeight()/2.0);var dist=distance(centerX,centerY,mouseX,mouseY);var newSize=(1-Math.min(1,Math.max(0,dist/proximity)))*iconDiff+iconSmall;jQuery(this).find("a").css({width:newSize});});dock1.find("li").each(function(){var centerX=jQuery(this).offset().left+(jQuery(this).outerWidth()/2.0);var centerY=jQuery(this).offset().top+(jQuery(this).outerHeight()/2.0);var dist=distance(centerX,centerY,mouseX,mouseY);var newSize=(1-Math.min(1,Math.max(0,dist/proximity)))*iconDiff+iconSmall;jQuery(this).find("a").css({width:newSize});});dock2.find("li").each(function(){var centerX=jQuery(this).offset().left+(jQuery(this).outerWidth()/2.0);var centerY=jQuery(this).offset().top+(jQuery(this).outerHeight()/2.0);var dist=distance(centerX,centerY,mouseX,mouseY);var newSize=(1-Math.min(1,Math.max(0,dist/proximity)))*iconDiff+iconSmall;jQuery(this).find("a").css({width:newSize});});}
jQuery('.accordionButtonfaq').click(function()
{jQuery('.accordionButtonfaq').removeClass('on');jQuery('.accordionContentfaq').slideUp('normal');if(jQuery(this).next().is(':hidden')==true)
{jQuery(this).addClass('on');jQuery(this).next().slideDown('normal');}});jQuery(function($){$("#social").delay(6000).queue(function(){$(".fbConnectWidgetTopmost").css({"border-style":"hidden"});});});jQuery('#getaquote').submit(function(){var action=jQuery(this).attr('action');jQuery.post(action,{name:jQuery('#fullname').val(),email:jQuery('#qemail').val(),phone:jQuery('#phone').val(),product:jQuery('#product').val(),webmessage:jQuery('#webmessage').val()},function(data){jQuery('#getaquote #submit').attr('disabled','');jQuery('.response').remove();alert(data);jQuery('.response').slideDown();});return false;});});