#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Efergy3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Efergy")]
	public partial class Efergy3DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategory(Category instance);
    partial void UpdateCategory(Category instance);
    partial void DeleteCategory(Category instance);
    partial void InsertProductDetail(ProductDetail instance);
    partial void UpdateProductDetail(ProductDetail instance);
    partial void DeleteProductDetail(ProductDetail instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    #endregion
		
		public Efergy3DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Efergy3DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Efergy3DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Efergy3DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Efergy3DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Category> Categories
		{
			get
			{
				return this.GetTable<Category>();
			}
		}
		
		public System.Data.Linq.Table<ProductDetail> ProductDetails
		{
			get
			{
				return this.GetTable<ProductDetail>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Category")]
	public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _categoryid;
		
		private string _catname;
		
		private EntitySet<Product> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncategoryidChanging(int value);
    partial void OncategoryidChanged();
    partial void OncatnameChanging(string value);
    partial void OncatnameChanged();
    #endregion
		
		public Category()
		{
			this._Products = new EntitySet<Product>(new Action<Product>(this.attach_Products), new Action<Product>(this.detach_Products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int categoryid
		{
			get
			{
				return this._categoryid;
			}
			set
			{
				if ((this._categoryid != value))
				{
					this.OncategoryidChanging(value);
					this.SendPropertyChanging();
					this._categoryid = value;
					this.SendPropertyChanged("categoryid");
					this.OncategoryidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string catname
		{
			get
			{
				return this._catname;
			}
			set
			{
				if ((this._catname != value))
				{
					this.OncatnameChanging(value);
					this.SendPropertyChanging();
					this._catname = value;
					this.SendPropertyChanged("catname");
					this.OncatnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Product", Storage="_Products", ThisKey="categoryid", OtherKey="categoryid")]
		public EntitySet<Product> Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Category = this;
		}
		
		private void detach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Category = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductDetails")]
	public partial class ProductDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductDetailsId;
		
		private string _img1;
		
		private string _img2;
		
		private string _img3;
		
		private string _img4;
		
		private string _img5;
		
		private string _img6;
		
		private string _img7;
		
		private string _img8;
		
		private string _img9;
		
		private string _img10;
		
		private string _img11;
		
		private string _img12;
		
		private string _img13;
		
		private string _img14;
		
		private string _img15;
		
		private int _ProductId;
		
		private EntityRef<Product> _Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductDetailsIdChanging(int value);
    partial void OnProductDetailsIdChanged();
    partial void Onimg1Changing(string value);
    partial void Onimg1Changed();
    partial void Onimg2Changing(string value);
    partial void Onimg2Changed();
    partial void Onimg3Changing(string value);
    partial void Onimg3Changed();
    partial void Onimg4Changing(string value);
    partial void Onimg4Changed();
    partial void Onimg5Changing(string value);
    partial void Onimg5Changed();
    partial void Onimg6Changing(string value);
    partial void Onimg6Changed();
    partial void Onimg7Changing(string value);
    partial void Onimg7Changed();
    partial void Onimg8Changing(string value);
    partial void Onimg8Changed();
    partial void Onimg9Changing(string value);
    partial void Onimg9Changed();
    partial void Onimg10Changing(string value);
    partial void Onimg10Changed();
    partial void Onimg11Changing(string value);
    partial void Onimg11Changed();
    partial void Onimg12Changing(string value);
    partial void Onimg12Changed();
    partial void Onimg13Changing(string value);
    partial void Onimg13Changed();
    partial void Onimg14Changing(string value);
    partial void Onimg14Changed();
    partial void Onimg15Changing(string value);
    partial void Onimg15Changed();
    partial void OnProductIdChanging(int value);
    partial void OnProductIdChanged();
    #endregion
		
		public ProductDetail()
		{
			this._Product = default(EntityRef<Product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDetailsId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductDetailsId
		{
			get
			{
				return this._ProductDetailsId;
			}
			set
			{
				if ((this._ProductDetailsId != value))
				{
					this.OnProductDetailsIdChanging(value);
					this.SendPropertyChanging();
					this._ProductDetailsId = value;
					this.SendPropertyChanged("ProductDetailsId");
					this.OnProductDetailsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img1", DbType="NVarChar(MAX)")]
		public string img1
		{
			get
			{
				return this._img1;
			}
			set
			{
				if ((this._img1 != value))
				{
					this.Onimg1Changing(value);
					this.SendPropertyChanging();
					this._img1 = value;
					this.SendPropertyChanged("img1");
					this.Onimg1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img2", DbType="NVarChar(MAX)")]
		public string img2
		{
			get
			{
				return this._img2;
			}
			set
			{
				if ((this._img2 != value))
				{
					this.Onimg2Changing(value);
					this.SendPropertyChanging();
					this._img2 = value;
					this.SendPropertyChanged("img2");
					this.Onimg2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img3", DbType="NVarChar(MAX)")]
		public string img3
		{
			get
			{
				return this._img3;
			}
			set
			{
				if ((this._img3 != value))
				{
					this.Onimg3Changing(value);
					this.SendPropertyChanging();
					this._img3 = value;
					this.SendPropertyChanged("img3");
					this.Onimg3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img4", DbType="NVarChar(MAX)")]
		public string img4
		{
			get
			{
				return this._img4;
			}
			set
			{
				if ((this._img4 != value))
				{
					this.Onimg4Changing(value);
					this.SendPropertyChanging();
					this._img4 = value;
					this.SendPropertyChanged("img4");
					this.Onimg4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img5", DbType="NVarChar(MAX)")]
		public string img5
		{
			get
			{
				return this._img5;
			}
			set
			{
				if ((this._img5 != value))
				{
					this.Onimg5Changing(value);
					this.SendPropertyChanging();
					this._img5 = value;
					this.SendPropertyChanged("img5");
					this.Onimg5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img6", DbType="NVarChar(MAX)")]
		public string img6
		{
			get
			{
				return this._img6;
			}
			set
			{
				if ((this._img6 != value))
				{
					this.Onimg6Changing(value);
					this.SendPropertyChanging();
					this._img6 = value;
					this.SendPropertyChanged("img6");
					this.Onimg6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img7", DbType="NVarChar(MAX)")]
		public string img7
		{
			get
			{
				return this._img7;
			}
			set
			{
				if ((this._img7 != value))
				{
					this.Onimg7Changing(value);
					this.SendPropertyChanging();
					this._img7 = value;
					this.SendPropertyChanged("img7");
					this.Onimg7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img8", DbType="NVarChar(MAX)")]
		public string img8
		{
			get
			{
				return this._img8;
			}
			set
			{
				if ((this._img8 != value))
				{
					this.Onimg8Changing(value);
					this.SendPropertyChanging();
					this._img8 = value;
					this.SendPropertyChanged("img8");
					this.Onimg8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img9", DbType="NVarChar(MAX)")]
		public string img9
		{
			get
			{
				return this._img9;
			}
			set
			{
				if ((this._img9 != value))
				{
					this.Onimg9Changing(value);
					this.SendPropertyChanging();
					this._img9 = value;
					this.SendPropertyChanged("img9");
					this.Onimg9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img10", DbType="NVarChar(MAX)")]
		public string img10
		{
			get
			{
				return this._img10;
			}
			set
			{
				if ((this._img10 != value))
				{
					this.Onimg10Changing(value);
					this.SendPropertyChanging();
					this._img10 = value;
					this.SendPropertyChanged("img10");
					this.Onimg10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img11", DbType="NVarChar(MAX)")]
		public string img11
		{
			get
			{
				return this._img11;
			}
			set
			{
				if ((this._img11 != value))
				{
					this.Onimg11Changing(value);
					this.SendPropertyChanging();
					this._img11 = value;
					this.SendPropertyChanged("img11");
					this.Onimg11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img12", DbType="NVarChar(MAX)")]
		public string img12
		{
			get
			{
				return this._img12;
			}
			set
			{
				if ((this._img12 != value))
				{
					this.Onimg12Changing(value);
					this.SendPropertyChanging();
					this._img12 = value;
					this.SendPropertyChanged("img12");
					this.Onimg12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img13", DbType="NVarChar(MAX)")]
		public string img13
		{
			get
			{
				return this._img13;
			}
			set
			{
				if ((this._img13 != value))
				{
					this.Onimg13Changing(value);
					this.SendPropertyChanging();
					this._img13 = value;
					this.SendPropertyChanged("img13");
					this.Onimg13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img14", DbType="NVarChar(MAX)")]
		public string img14
		{
			get
			{
				return this._img14;
			}
			set
			{
				if ((this._img14 != value))
				{
					this.Onimg14Changing(value);
					this.SendPropertyChanging();
					this._img14 = value;
					this.SendPropertyChanged("img14");
					this.Onimg14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img15", DbType="NVarChar(MAX)")]
		public string img15
		{
			get
			{
				return this._img15;
			}
			set
			{
				if ((this._img15 != value))
				{
					this.Onimg15Changing(value);
					this.SendPropertyChanging();
					this._img15 = value;
					this.SendPropertyChanged("img15");
					this.Onimg15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					if (this._Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_ProductDetail", Storage="_Product", ThisKey="ProductId", OtherKey="productid", IsForeignKey=true)]
		public Product Product
		{
			get
			{
				return this._Product.Entity;
			}
			set
			{
				Product previousValue = this._Product.Entity;
				if (((previousValue != value) 
							|| (this._Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product.Entity = null;
						previousValue.ProductDetails.Remove(this);
					}
					this._Product.Entity = value;
					if ((value != null))
					{
						value.ProductDetails.Add(this);
						this._ProductId = value.productid;
					}
					else
					{
						this._ProductId = default(int);
					}
					this.SendPropertyChanged("Product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _productid;
		
		private string _proname;
		
		private System.Nullable<double> _rating;
		
		private double _price;
		
		private System.Nullable<double> _minimalprice;
		
		private System.Nullable<double> _oldprice;
		
		private string _image;
		
		private int _categoryid;
		
		private string _video;
		
		private string _tekstDetali;
		
		private string _slikiDetali;
		
		private EntitySet<ProductDetail> _ProductDetails;
		
		private EntityRef<Category> _Category;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductidChanging(int value);
    partial void OnproductidChanged();
    partial void OnpronameChanging(string value);
    partial void OnpronameChanged();
    partial void OnratingChanging(System.Nullable<double> value);
    partial void OnratingChanged();
    partial void OnpriceChanging(double value);
    partial void OnpriceChanged();
    partial void OnminimalpriceChanging(System.Nullable<double> value);
    partial void OnminimalpriceChanged();
    partial void OnoldpriceChanging(System.Nullable<double> value);
    partial void OnoldpriceChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OncategoryidChanging(int value);
    partial void OncategoryidChanged();
    partial void OnvideoChanging(string value);
    partial void OnvideoChanged();
    partial void OntekstDetaliChanging(string value);
    partial void OntekstDetaliChanged();
    partial void OnslikiDetaliChanging(string value);
    partial void OnslikiDetaliChanged();
    #endregion
		
		public Product()
		{
			this._ProductDetails = new EntitySet<ProductDetail>(new Action<ProductDetail>(this.attach_ProductDetails), new Action<ProductDetail>(this.detach_ProductDetails));
			this._Category = default(EntityRef<Category>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int productid
		{
			get
			{
				return this._productid;
			}
			set
			{
				if ((this._productid != value))
				{
					this.OnproductidChanging(value);
					this.SendPropertyChanging();
					this._productid = value;
					this.SendPropertyChanged("productid");
					this.OnproductidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string proname
		{
			get
			{
				return this._proname;
			}
			set
			{
				if ((this._proname != value))
				{
					this.OnpronameChanging(value);
					this.SendPropertyChanging();
					this._proname = value;
					this.SendPropertyChanged("proname");
					this.OnpronameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rating", DbType="Float")]
		public System.Nullable<double> rating
		{
			get
			{
				return this._rating;
			}
			set
			{
				if ((this._rating != value))
				{
					this.OnratingChanging(value);
					this.SendPropertyChanging();
					this._rating = value;
					this.SendPropertyChanged("rating");
					this.OnratingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float NOT NULL")]
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minimalprice", DbType="Float")]
		public System.Nullable<double> minimalprice
		{
			get
			{
				return this._minimalprice;
			}
			set
			{
				if ((this._minimalprice != value))
				{
					this.OnminimalpriceChanging(value);
					this.SendPropertyChanging();
					this._minimalprice = value;
					this.SendPropertyChanged("minimalprice");
					this.OnminimalpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oldprice", DbType="Float")]
		public System.Nullable<double> oldprice
		{
			get
			{
				return this._oldprice;
			}
			set
			{
				if ((this._oldprice != value))
				{
					this.OnoldpriceChanging(value);
					this.SendPropertyChanging();
					this._oldprice = value;
					this.SendPropertyChanged("oldprice");
					this.OnoldpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryid", DbType="Int NOT NULL")]
		public int categoryid
		{
			get
			{
				return this._categoryid;
			}
			set
			{
				if ((this._categoryid != value))
				{
					if (this._Category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncategoryidChanging(value);
					this.SendPropertyChanging();
					this._categoryid = value;
					this.SendPropertyChanged("categoryid");
					this.OncategoryidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_video", DbType="VarChar(255)")]
		public string video
		{
			get
			{
				return this._video;
			}
			set
			{
				if ((this._video != value))
				{
					this.OnvideoChanging(value);
					this.SendPropertyChanging();
					this._video = value;
					this.SendPropertyChanged("video");
					this.OnvideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tekstDetali", DbType="NVarChar(MAX)")]
		public string tekstDetali
		{
			get
			{
				return this._tekstDetali;
			}
			set
			{
				if ((this._tekstDetali != value))
				{
					this.OntekstDetaliChanging(value);
					this.SendPropertyChanging();
					this._tekstDetali = value;
					this.SendPropertyChanged("tekstDetali");
					this.OntekstDetaliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slikiDetali", DbType="NVarChar(MAX)")]
		public string slikiDetali
		{
			get
			{
				return this._slikiDetali;
			}
			set
			{
				if ((this._slikiDetali != value))
				{
					this.OnslikiDetaliChanging(value);
					this.SendPropertyChanging();
					this._slikiDetali = value;
					this.SendPropertyChanged("slikiDetali");
					this.OnslikiDetaliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_ProductDetail", Storage="_ProductDetails", ThisKey="productid", OtherKey="ProductId")]
		public EntitySet<ProductDetail> ProductDetails
		{
			get
			{
				return this._ProductDetails;
			}
			set
			{
				this._ProductDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Product", Storage="_Category", ThisKey="categoryid", OtherKey="categoryid", IsForeignKey=true)]
		public Category Category
		{
			get
			{
				return this._Category.Entity;
			}
			set
			{
				Category previousValue = this._Category.Entity;
				if (((previousValue != value) 
							|| (this._Category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Category.Entity = null;
						previousValue.Products.Remove(this);
					}
					this._Category.Entity = value;
					if ((value != null))
					{
						value.Products.Add(this);
						this._categoryid = value.categoryid;
					}
					else
					{
						this._categoryid = default(int);
					}
					this.SendPropertyChanged("Category");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProductDetails(ProductDetail entity)
		{
			this.SendPropertyChanging();
			entity.Product = this;
		}
		
		private void detach_ProductDetails(ProductDetail entity)
		{
			this.SendPropertyChanging();
			entity.Product = null;
		}
	}
}
#pragma warning restore 1591
